### ISSUE TITLE
failed to run the code one machine

### ISSUE THREAD

**Issue by cjlin1** [yu54ku/xml-cnn#4]
As the title. I can run it on one machine but on another machine
it failed with the following message. Do you see why this happened?
Many thanks

```
$ python3 train.py 

============================== Normal Train Mode ==============================

------------------------------------ Params -----------------------------------
[('batch_size', 64), ('cache_path', 'cache'), ('measure', 'p@1'), ('sequence_length', 500)]
-------------------------------------------------------------------------------

--------------------------------- Hyper Params --------------------------------
[('d_max_pool_p', [125, 128, 128]), ('filter_channels', 128), ('filter_sizes', [2, 4, 8]), ('hidden_dims', 512), ('learning_rate', 0.0005099137446356937), ('stride', [2, 1, 1])]
-------------------------------------------------------------------------------

Loading data...  /home/cjlin/.local/lib/python3.6/site-packages/torchtext/data/field.py:36: UserWarning: RawField class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/home/cjlin/.local/lib/python3.6/site-packages/torchtext/data/field.py:150: UserWarning: Field class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/home/cjlin/.local/lib/python3.6/site-packages/torchtext/data/example.py:68: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)
/home/cjlin/.local/lib/python3.6/site-packages/torchtext/data/example.py:78: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)
Done.
Converting text to ID...  Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 106, in main
    trainer.preprocess()
  File "/home/cjlin/xml-cnn/build_problem.py", line 151, in preprocess
    self.TEXT.vocab.load_vectors("glove.6B.300d")
  File "/home/cjlin/.local/lib/python3.6/site-packages/torchtext/vocab.py", line 184, in load_vectors
    vectors[idx] = pretrained_aliases[vector](**kwargs)
  File "/home/cjlin/.local/lib/python3.6/site-packages/torchtext/vocab.py", line 487, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/home/cjlin/.local/lib/python3.6/site-packages/torchtext/vocab.py", line 326, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/home/cjlin/.local/lib/python3.6/site-packages/torchtext/vocab.py", line 368, in cache
    with zipfile.ZipFile(dest, "r") as zf:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by yu54ku** [comment]
It looks to me like the error is caused by the library.
Are you running this program in the recommended environment (using Anaconda and `requirements.yml`)?

**Comment by cjlin1** [comment]
No, I am not using conda as it's not available in our system.
The code reported some packages are missing and then I pip install them.
By this it works on one machine but not the other.
Thanks

**Comment by yu54ku** [comment]
I havn't tested it in any environment other than Anaconda, which was created using `requirements.yml`.
We can't guarantee that it will work outside of this environment.
You are responsible for that.
